---
- name: ls
  hosts: boon-server
  tasks:
    - name: list file
      command: ls -a
      register: command_output

    - name: Display command output
      debug:
       var: command_output.stdout_lines
